/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Spyro the Dragon)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80060D10u
#define func_80060D10 BootEntry  /* alias */
